### ISSUE TITLE
eqos-1932: Verify whether Formatted Text renders HTML correctly

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#364]
Add a Formatted Text Portlet
Enter a Title, click on the HTML button and enter the text below in the HTML source editor
<ol> 
    <li>Test1</li> 
    <li>Test2</li> 
</ol> 
<ul> 
    <li>Test3</li> 
    <li>Test4</li> 
</ul> 

The new Formatted Text portlet should be added and the <ol> and <ul> should be rendered correctly.

<ol> should produce a numbered list, 
<ul> should produce a list with bullet points. 

This is not working.

**Comment by emcgarrahan** [comment]
Also broken in 6.4QA3

**Comment by doolse** [comment]
The problem is because of a bad CSS style - https://stackoverflow.com/questions/40910926/why-overflow-yhidden-of-html-lists-makes-bullet-number-to-be-invisible

The formatted text portlet has "overflow-y: hidden" for some reason (not sure if it's a good reason or not..)

Also the bullet points are hidden because that's the default equella style for unordered lists, we probably should turn them back on in this and the scripted portlet but I have no idea how this hasn't been fixed as I suspect it's been like it for many versions

**Comment by mrblippy** [comment]
Still displays without the bullets or numbers
![capture](https://user-images.githubusercontent.com/4625498/31978711-5b5fd23c-b98e-11e7-911a-b5bba710b59e.PNG)

**Comment by doolse** [comment]
@mrblippy I think that was cached CSS yeah?

**Comment by mrblippy** [comment]
Yep, once the cached css was refreshed it was all good
