### ISSUE TITLE
Prepare a NOTICE File with accurate license info for each dependency

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#4]
Typically done with a build plug in

**Comment by bjagg** [comment]
This can be automated with Maven, if we use that tool.

**Comment by emcgarrahan** [comment]
Research Gradle options

**Comment by bjagg** [comment]
https://github.com/eskatos/honker-gradle looks like a solution for this.

**Comment by doolse** [comment]
I did a bit of work on a branch called "gradle-test", to summarize:

- I wrote a purescript script for converting our "deps.txt" json format into other formats - gradle is implemented
- I created a proof of concept gradle build which builds the projects in "Platform" 
    - Inter-project dependencies were manually created but we could automate this using the JPF manifests
- Added the honker gradle plugin and ran it (there were a few unresolved things but it did end up spitting out a "DEPENDENCIES.txt" which seemed ok

My personal preference would be to be use SBT instead of Gradle as I've already gone through the process of changing the EQUELLA (EPS) build to it already. It has the equivalent plugins for license reports and ensuring source files have licese headers
    - https://github.com/sbt/sbt-license-report
    - https://github.com/sbt/sbt-header

Either way i'm going to do a similar experiment with SBT

**Comment by bjagg** [comment]
Jolse looking into this

**Comment by bjagg** [comment]
FYI here is the Apereo Maven plugin for this: https://github.com/Jasig/maven-notice-plugin

**Comment by bjagg** [comment]
Awaiting SBT build tool task

**Comment by bjagg** [comment]
@doolse You mentioned this was resolved with SBT. Can we close this or is there more work to do?

**Comment by doolse** [comment]
The report has been updated, there is a few deps which the tool did not find licenses for (not sure how it finds them), which we might need to add overrides for if we want it to be more accurate.

**Comment by bjagg** [comment]
I think this effort is complete. We may still need to add some dependency overrides, but the file is not generated.
