### ISSUE TITLE
apidocs.do page contains lots of errors

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#424]
![capture](https://user-images.githubusercontent.com/4625498/35371070-fd82776e-01e5-11e8-96bc-f3cfa2f616e5.PNG) 

Also, the page keeps refreshing whenever you click the try it out button for any of the endpoints

**Comment by doolse** [comment]
I've upgraded swagger-ui and now it only reports the single error which is caused by the 
"UuidReference" class having a property called "$ref" which is a reserved word for swagger REST API description files now. 

We could fix this by changing the name of the property to "ref" and perhaps also supporting "$ref" as a write only value. It's still a breaking change for any old code wanting to edit it (such as our autotests).

@abidingotter thoughts?

**Comment by abidingotter** [comment]
Log a bug with Swagger? :)   It's a legit JSON property name.

Maybe we can create a new version of our API and remove all the current backwards compatible fixes? (There are only a few from memory)

**Comment by doolse** [comment]
Apparently the latest swagger-ui fixed their $ref parsing

**Comment by mrblippy** [comment]
fixed

**Comment by mrblippy** [comment]
The page refresh when clicking 'try it out' is back when using the old ui, works fine on the new ui though

**Comment by doolse** [comment]
Closing this and creating a new one as a client has found this in 6.6 too
