### ISSUE TITLE
Hidden pages containing the same metadata targets reset on page navigation

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#433]
1. Setup a wizard with two 'first' pages where one or the other will display (eg. based on the role of the user), and a second page.
2. Configure a radio button widget that has different values on each of the 'first' pages, **but keys off of the same metadata target**.
3. Save the wizard editor.
4. Begin an item contribution to that collection.  Notice that selecting a value for the radio buttons, navigating to the second page, and then returning to the first, clears out your selected value of the radio buttons.   Using an Edit Box widget does not cause this behavior.

When setting the metadata field of the radio buttons on the latter 'first' page, Equella gives a warning that it's not recommended to have the same metadata field on separate pages.  However, this seems like a valid flow (having multiple pages using the same metadata targets, when all but one of the pages will be hidden). If you had a widget keying off the same field in two different spots and visible at the same time, I would consider it a poor design choice. This however, seems like a reasonable way to build a wizard.

Interested as well to hear from the community - should this be a supported feature of Equella, or a known limitation?

**Comment by cbeach47** [comment]
Taking a look at this - interested to hear if folks know of a reason that this should not be supported in Equella.

**Comment by phette23** [comment]
Just wanted to add that, even if it's perhaps not a feature that's wanted in EQUELLA, it definitely has behaved this way in the past (e.g. the metadata field would not be wiped out upon navigating to later pages, this was the case for us on 6.4 QA1 at least) and the issue is a regression.

For us, contribution wizards frequently have this set up when a certain kind of item cannot be contributed by a certain user group. We don't want students uploading administrative documents to an academic program's collection. The alternative way of implementing this is with one large wizard page, but that quickly becomes clunky. Specifically, if different types of items have many unique fields then each form control needs it's own script rather than placing just two scripts on two separate pages that then list the controls unique to each item type.

**Comment by cbeach47** [comment]
As I began to explore a fix in the master branch, I realized my test scenario _worked_.  I confirmed in a local install that 6.4-QA3, and the 6.5-Stable _tag_ fails.  Upgrading to a build with the latest code from the 'stable' branch (doesn't need to be the bleeding edge of master) allows the scenario to work.  My theory is that it's due to #419 or possibly #406 , either way, this doesn't look to be an issue anymore in the latest 6.5 Stable.
