### ISSUE TITLE
New build components

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#437]
With the latest commits in master, it looks like we should update the readme and developer documentation.  I am happy to push out an update, but want to get @doolse thoughts first:

- Is it true Yarn, NodeJS, Browsify are now required to compile and build Equella?  Any know specific versions?  I found that the default NodeJS in Ubuntu was not a high enough level, but the latest NodeJS worked.
- Building Equella inside of intelliJ fails to have the REST API apidocs.do show up (complained about missing bundle.js).  After a sbt compile on the command line and a refresh in intelliJ, running equellaserver inside of intelliJ worked better.  Did you come up with a cleaner way for it to be smoother inside intelliJ, or does the sbt compile tasks just need to be run now if any of the frontend code changes?

**Comment by doolse** [comment]
> Is it true Yarn, NodeJS, Browsify are now required to compile and build Equella? Any know specific versions? I found that the default NodeJS in Ubuntu was not a high enough level, but the latest NodeJS worked.

Yes, currently Yarn. NodesJS and browserify are needed to build master because of swagger-ui. However the build setup is likely to change a bit due to the React UI, so if you did document that it'll probably need to be updated very soon when the React branch is merged in. (I'd like to try and get the least number of pre-installs required, hopefully just Yarn).

```
jolz@boorah:~/equella/Equella$ yarn -v
1.3.2
jolz@boorah:~/equella/Equella$ node -v
v6.11.4
```

As far as running in IntelliJ goes, nothing has really changed as it's always only compiled sources and copied resources over. It doesn't do any of the special tasks which SBT needs to perform such as:

* Generating AXIS SOAP code
* Building the BIRT engine
* Building the admin console jar + applets
* Running YUI on JS files

However, for the JS (purescript) files I added yarn scripts for running a "watched build" which recompiles and bundles up the javascript and outputs it to the correct classes dir for dev mode. See the "watch*" scripts in: `Source/Plugins/Core/com.equella.core/ps/package.json`

**Comment by cbeach47** [comment]
Thanks @doolse - I'm just going to reference this issue and the Scala / Java google group thread so potential new developers are aware of the changes and save the more detailed documentation updates for once the React UI is merged in.
