### ISSUE TITLE
Course editing web UI

### ISSUE THREAD

**Issue by doolse** [equella/Equella#462]
Create a new UI for listing and editing copyright courses which use the REST API.

- [x] Finish i18n
- [x] Make sure name and description editing works properly with the i18n REST props
- [x] Validation
- [x] Spinners for when API calls are happening
- [x] Confirmation of save (snackbar?)
- [x] Display name of course you're editing in app bar
- [x] Adding new permission should open a dialog to select which one

**Comment by abidingotter** [comment]
There is a spinner when loading up a course, but no spinners when saving as I wasn't sure what to do there.  (It looks really bad when show the loading spinner when you save)
Additionally, the spinner should probably only show after a certain (short) duration, otherwise it just flickers on and off and is distracting.
