### ISSUE TITLE
Bulk Rollover activations: execute button displayed prematurely

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#557]
You shouldn't be able to execute until you have filled out the info on the next screen
![capture](https://user-images.githubusercontent.com/4625498/44245912-b5f12b00-a21e-11e8-8ab9-125970df26f8.PNG)

**Comment by edalex-ian** [comment]
Discussed with PM, and for now those using it know what they have to do so we can look at in 2019.1.

**Comment by abidingotter** [comment]
This is actually working as intended.  
The reason I couldn't reproduce the issue is because I didn't have default dates for courses, and it wouldn't let me execute from the first page because not all required data was filled in. 
Technically you *should* be able to Execute from the first page, and optionally go to Next if you want to change the values.

**Comment by cathfitz** [comment]
@abidingotter @edalex-ian Looking back at the doco from 6.3 when we enhanced the bulk rollover function, you have to go to the details page to make sure your default options are correct before you execute. I also notice that the default option of "Use activation's current course" is longer available and needs to be restored ASAP as this is a default used by many.
![rollover](https://user-images.githubusercontent.com/32081370/51446230-39c9b900-1d63-11e9-86bd-c0162cd4d765.png)

**Comment by edalex-ian** [comment]
Heya @cathfitz , could you please raise a new issue for the missing 'Use activation's current course'?

**Comment by mrblippy** [comment]
Verified in 2019.1
