### ISSUE TITLE
Add ability to upload logo and select colour palette for new UI

### ISSUE THREAD

**Issue by edalex-ian** [equella/Equella#638]
**Describe the solution you'd like**

Ability to upload institution logo (preferably by using drag and drop) and selection of colour palette. A set of pre-defined themes will be provided, plus the ability to override with custom colours.

(This has already been done as part of #625 - but we need the GH ticket at least for testing. Note that the implementation is slightly different to the above requirement which was from the RDA process.)

**Comment by mrblippy** [comment]
Looks all good, except the three icons at the top right of every other page in the new ui aren't present on this page. Was that intentional?

![icons](https://user-images.githubusercontent.com/4625498/49974573-1d7d7400-ff8e-11e8-8ae0-d1ec4b7c2c05.PNG)

Also, that user icon doesn't seem to react to colour changes

**Comment by edalex-ian** [comment]
Above issues addressed in PR #659.

**Comment by doolse** [comment]
Can confirm that notifications show up and icons are the same colour
