### ISSUE TITLE
Advanced search parameters can get cleared out when they shouldn't

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#766]
**Describe the bug**
Seems to be something funky about how the bookmarked editquery and submitwizard paramaters are being handled (SearchQueryModel)

**To Reproduce**

1. Setup an advanced search 
2. Perform an advanced search, use an advanced search query that will return more than one page of results
3. Click on any of the results on the first page, to take you to an item summary page
4. Click the search button int the left menu
5. Notice it has forgotten the where clause that you entered in step 2
6. The where clause would have been remembered if you accessed an item from page 2 of the search

**Expected behavior**
The where clause for an advanced search should get saved in the session, and displayed when you access the search page again 
![capture](https://user-images.githubusercontent.com/4625498/53924823-a6113980-40d1-11e9-8693-df13a3ec3057.PNG)

**Platform:**

- OpenEquella Version: 6.4, 6.5, 6.6, 2018.2, 2019.1
- OS: Windows 10
- Browser Chrome

**Comment by carl-edalex** [comment]
Just as a further observation, if you go to an advanced search and put in a criterion as well as a basic search keyword, and then navigate anywhere else (Dashboard, a hierarchy, or even clicking on the Search in the left navigation), it forgets the advanced search query, but remembers the basic search query.  

I suppose the question is whether or not it should remember an advanced search query.  Lets say you have 3 different advanced searches, and a user within the same login session uses all three of them.  Is it reasonable that if a user later on decides to perform another advanced search that it remembers all of the query parameters for that specific advanced search that they'd previously performed?

**Comment by garnetberrry** [comment]
Hi @carl-edalex,

I thought I would offer some context to the issue raised by the user in this case.

In short this issue is less about how the advanced search query should function (regarding the 3 search example) and more about how the current method is not consistent.

As per the explanation above, the issue arrises when you perform an advanced search and click on any item within the first page.  At this point if you go back to search the advanced search is not saved in the same way it does if you perform same process for page 2 onwards.

Hope this makes sense.

**Comment by carl-edalex** [comment]
Sorry @garnetberrry - I don't mean to throw confusion into the issue.  I understand that the issue is that search queries aren't being saved properly or consistently when leaving and returning to a search, and I'm not sure how it is "supposed" to be saved.  I'm just highlighting that complex scenarios such as multiple advanced searches - would each be saved contextually or is it simply the last advanced search?  So I'll withdraw now ... :-)

**Comment by cathfitz** [comment]
Tested and closed
